title: Full Stack Course
tagline: PlexTech Curriculum
description: A course covering the basics of full-stack web development and software engineering principles powered by PlexTech, UC Berkeley's premier technology consulting club.
author: Eugene Chao
baseurl: "/"
url: ""

theme: just-the-docs

aux_links:
  "PlexTech":
    - "https://plextech.berkeley.edu/"
  "Dark Mode":
    - "#"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - vendor/bundle/
  - yarn.lock